### ISSUE TITLE
Build error phantomjs

### ISSUE THREAD

**Issue by longtran84** [mwasiluk/angular-surveys#69]
npm ERR! code 1
npm ERR! path /home/j2ee/Downloads/angular-surveys-master/node_modules/phantomjs
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! PhantomJS not found on PATH
npm ERR! Phantom installation failed TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
npm ERR!     at validateString (internal/validators.js:120:11)
npm ERR!     at Object.join (path.js:1039:7)
npm ERR!     at findSuitableTempDirectory (/home/j2ee/Downloads/angular-surveys-master/node_modules/phantomjs/install.js:127:30)
npm ERR!     at /home/j2ee/Downloads/angular-surveys-master/node_modules/phantomjs/install.js:476:19
npm ERR!     at nextTickCallback (/home/j2ee/Downloads/angular-surveys-master/node_modules/kew/kew.js:47:28)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
npm ERR!   code: 'ERR_INVALID_ARG_TYPE'
npm ERR! } TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
npm ERR!     at validateString (internal/validators.js:120:11)
npm ERR!     at Object.join (path.js:1039:7)
npm ERR!     at findSuitableTempDirectory (/home/j2ee/Downloads/angular-surveys-master/node_modules/phantomjs/install.js:127:30)
npm ERR!     at /home/j2ee/Downloads/angular-surveys-master/node_modules/phantomjs/install.js:476:19
npm ERR!     at nextTickCallback (/home/j2ee/Downloads/angular-surveys-master/node_modules/kew/kew.js:47:28)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:79:11)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/j2ee/.npm/_logs/2023-11-06T11_41_30_811Z-debug-0.log

**Comment by longtran84** [comment]
@jorge-1409 can you help me on this issue?
